#!/bin/sh

change_dir() {
  cd $1 && [[ $(pwd) == */projects* || $(pwd) == */work* ]] && change_node_version
}

alias cp="cp -iv"
alias mv="mv -iv"
alias ag="ag --hidden --ignore .git"
alias vim=nvim
alias tmux="tmux -2"
# alias cd="change_dir"

if [[ $OSTYPE == linux* ]]; then
  alias afk="i3lock -c 000000"
  alias open="xdg-open"
  alias rm="rm -vI"
  # alias scrot="scrot -s -u -b -c 5"
  alias uireload="xrdb -merge $HOME/.Xresources"
  alias xclip="xclip -selection c"
  # alias ls="ls --colors=auto"
elif [[ $OSTYPE == darwin* ]]; then
  alias python=python3
  alias pip=pip3
  alias ngrok=~/Applications/ngrok
  alias rm="rm -vi"
  alias ls="ls -G"
fi
