#!/bin/sh

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export NVM_DIR="$HOME/.nvm"
export EDITOR=$(which vim)

if [[ $OSTYPE == linux* ]]; then
  export EDITOR="$(which nvim)"
  # hidpi for gtk apps
  export GDK_SCALE=2.5
  export GTK_SCALE=1.5
  export GDK_DPI_SCALE=0.5
  export GTK_DPI_SCALE=0.5
  export QT_SCALE_FACTOR=1.5
  export QT_DEVICE_PIXEL_RATIO=1.5
  export QT_AUTO_SCREEN_SET_FACTOR=0
  # the default time is too long, this is used when changing vim modes in zsh
  export KEYTIMEOUT=1
fi
