#!/bin/sh

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export NVM_DIR="$HOME/.nvm"
export EDITOR=$(which vim)

if [[ $OSTYPE == linux* ]]; then
  export EDITOR="$(which nvim)"
  export GDK_SCALE=1
  export GDK_DPI_SCALE=1
  export GTK_SCALE=1
  export GTK_DPI_SCALE=1
  export QT_SCALE_FACTOR=1.5
  export QT_DEVICE_PIXEL_RATIO=1
  export QT_AUTO_SCREEN_SET_FACTOR=0
  # the default time is too long, this is used when changing vim modes in zsh
  export KEYTIMEOUT=1

  export ANDROID_SDK=$HOME/Android/Sdk
  export ANDROID_SDK_ROOT=$HOME/Android/Sdk
fi
