#!/bin/sh

encrypt() {
  if [[ $1 == *.gpg ]]; then
    # remove the .gpg extension
    local output_file=${1%.*}

    gpg -d -o $output_file $1 && rm $1

    [[ $output_file == *.gz ]] && tar xzf $output_file && rm $output_file

    unset output_file
  else
    # symmetric: encrypt with a symmetric cipher using a passphrase
    # no-symkey-cache: disable the cache of the passphrase

    # in case of a directory, compress, encrypt it and remove the compressed file
    [[ -d $1 ]] && tar czf $1.tar.gz $1 && gpg --symmetric --cipher-algo AES256 --no-symkey-cache $1.tar.gz && \
      rm -r $1 $1.tar.gz
    # in case of a file, encrypt it and remove original file
    [[ -f $1 ]] && gpg --symmetric --cipher-algo AES256 --no-symkey-cache $1 && rm $1
  fi
}

change_mac() {
  if [[ "$EUID" -ne 0 ]]; then
    echo "Please run as root"
    exit 1
  fi

  local CURRENT_ADDR=`ifconfig en0 | grep ether | awk '{print $2}'`
  local NEW_ADDR=`openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'`

  sudo ifconfig en0 ether $NEW_ADDR

  echo "Changed $CURRENT_ADDR for $NEW_ADDR"
}
