#!/bin/sh

delim="|"
path=$HOME/dotfiles/scripts

get_status() {
  # ie: 49%
  battery=$(cat /sys/class/power_supply/BAT0/capacity)%
  # date and time in the following format "Thu 12/07/1990 15:49"
  date=$(date '+%a %d/%m/%G %H:%M')
  # up or down
  internet=$(cat /sys/class/net/wlp3s0/operstate)
  volume=$(pactl list sinks | grep Volume | head -n 1 | awk -F '/' '{ print $2 }')

  echo $internet $delim b: $battery $delim s: $volume $delim $date
}

while :; do
  # echo "$(get_status | tr '\n' ' ')"
  xsetroot -name "$(get_status | tr '\n' ' ')"

  sleep 1m
done &
