#!/bin/sh

[[ $1 == '+' ]] && pactl -- set-sink-volume 0 +10%
[[ $1 == '-' ]] && pactl -- set-sink-volume 0 -10%
[[ $1 == '0' ]] && pactl -- set-sink-volume 0 0%

# refresh status bar
$HOME/dotfiles/arch/dwm_status_bar
